### ISSUE TITLE
Questions about some macro definitions

### ISSUE THREAD

**Issue by hong12234** [jaracil/pubsub-c#6]
HI，jaracil，I don't understand the meaning of the following macro definitions, can you tell me what they are used for?thanks for you
#define PS_SUB_PRIO(X) " p" #X
#define PS_SUB_HIDDEN " h"
#define PS_SUB_EMPTY " e"
#define PS_SUB_NOSTICKY " s"
#define PS_SUB_CHILDSTICKY " S"

**Comment by jaracil** [comment]
Hi.
They are suffixes flags for topic subscriptions.
You have use cases in tests e.g.:
ps_subscriber_t *s2 = ps_new_subscriber(10, PS_STRLIST("foo.bar" PS_SUB_HIDDEN));

PS_SUB_HIDDEN -> Subscription in hidden mode (Don't increment number of touched targets when publish)
PS_SUB_EMPTY -> Only receive message when subscriber buffer is empty (For wake up messages)
PS_SUB_NOSTICKY -> Don't want sticky message, only new messages since subscription
PS_SUB_CHILDSTICKY -> Receive all sticky messages from all path nodes
PS_SUB_PRIO(X) -> Give more or less priority to this subscription

See all use cases in tests.

Bye.

**Comment by hong12234** [comment]
> Hi. They are suffixes flags for topic subscriptions. You have use cases in tests e.g.: ps_subscriber_t *s2 = ps_new_subscriber(10, PS_STRLIST("foo.bar" PS_SUB_HIDDEN));
> 
> PS_SUB_HIDDEN -> Subscription in hidden mode (Don't increment number of touched targets when publish) PS_SUB_EMPTY -> Only receive message when subscriber buffer is empty (For wake up messages) PS_SUB_NOSTICKY -> Don't want sticky message, only new messages since subscription PS_SUB_CHILDSTICKY -> Receive all sticky messages from all path nodes PS_SUB_PRIO(X) -> Give more or less priority to this subscription
> 
> See all use cases in tests.
> 
> Bye.

glad thank you for your reply！
I'm starting to understand the test routine a little bit.
